apiVersion: v1
kind: Secret
metadata:
  name: aetherion-secrets
  namespace: aetherion
type: Opaque
stringData:
  # These are placeholders - replace with actual values in production
  JWT_SECRET_KEY: "replace-with-actual-secret-key"
  JWT_REFRESH_SECRET_KEY: "replace-with-actual-refresh-secret-key"
  MONGO_URI: "mongodb://mongo-service:27017/aetherion"
  REDIS_HOST: "redis-service"
  REDIS_PORT: "6379"
  OPENAI_API_KEY: "replace-with-actual-openai-key"
  ELEVENLABS_API_KEY: "replace-with-actual-elevenlabs-key"
  KAFKA_BOOTSTRAP_SERVERS: "kafka-service:9092" 